### ISSUE TITLE
anal category

### ISSUE THREAD

**Issue by AnXieTy7** [yoannchb-pro/discord-phub#2]
some links not working or not playing ( mostly gifs)

**Comment by AnXieTy7** [comment]
and if possible categorize it like (male to male )(female to female ) male to female 
so i can use it with gender role read + a command to filter the type 
i can help if needed ( discord tag AnXieTy | Shady#7777 )

**Comment by yoannchb-pro** [comment]
Ok I'm contacting you on discord. Do you have the version 1.0.5 of discord-phub ? And did you try to open the broken link in the browser ?

**Comment by AnXieTy7** [comment]
yes access declined in browser  
the latest virsion just updated it yea 
( i can fix that when i found a link that i know that is not working i just loop to search again if one if these links found ) 
https://discord.gg/KMZhHjfZ ( shared server to fond me faster )
