### ISSUE TITLE
Is a good module but ...

### ISSUE THREAD

**Issue by DerGoogler** [yoannchb-pro/discord-phub#4]
isn't useable in browsers... sad but true

**Comment by yoannchb-pro** [comment]
You can import manually the db into the discord-phub.js file

**Comment by yoannchb-pro** [comment]
I will add the browser file in 10min :)

**Comment by yoannchb-pro** [comment]
You can now use discord-phub.browser.js

**Comment by DerGoogler** [comment]
????
![image](https://user-images.githubusercontent.com/54764558/147709540-1822112c-ef29-4dd8-b718-68130ee0ec0e.png)

**Comment by DerGoogler** [comment]
returns it an url or element?

**Comment by DerGoogler** [comment]
ok. i added self an link return

**Comment by yoannchb-pro** [comment]
Do you have a discord to contact you it will be easier and we will able to talk about your pull request

**Comment by DerGoogler** [comment]
`Der_Googler#6289`

**Comment by yoannchb-pro** [comment]
ok I added. But I think you have fix all your problems
