### ISSUE TITLE
This XML file does not appear to have any style information associated with it. The document tree is shown below.

### ISSUE THREAD

**Issue by Mlob666** [yoannchb-pro/discord-phub#6]
Sometimes gifs/images are not shown in the embed and are not shown as a link, when you make a console.log with some links and enter them you get an error:

![image](https://user-images.githubusercontent.com/40547265/173164127-a911f3b8-edc5-4f0d-8d49-ecee0a36ebd5.png)

Example Link: https://cdn.discordapp.com/attachments/844668049126457354/854861217868677130/converted.gif

**Comment by yoannchb-pro** [comment]
In first, thx you. I'll check all the link in the next realese if you don't want to wait you can go in utils folder and launch link-check.js. Then copy files from db-check to db.

**Comment by yoannchb-pro** [comment]
I did the fixe in v1.0.7 and found 500 broken links
