### ISSUE TITLE
Error executing the Project/Command

### ISSUE THREAD

**Issue by Mlob666** [yoannchb-pro/discord-phub#8]
**NPM VERSION: 1.0.7**

**- Executing the Project:**

Code with literally nothing: 
![image](https://user-images.githubusercontent.com/40547265/174720189-4de54f85-1002-4c22-9884-6f9cafadb35f.png)

Error:
![image](https://user-images.githubusercontent.com/40547265/174719139-b1fdfc0c-b49c-417d-9c17-5eae58b03d70.png)

**- Executing The Command**

I decided just to put the categories in console

Code:
![image](https://user-images.githubusercontent.com/40547265/174720064-f66a6f5d-d6f3-4f5a-bcb4-3f92439327b4.png)

Error:
![image](https://user-images.githubusercontent.com/40547265/174719575-46fcfc56-54d2-472a-831e-464d1206a9dd.png)

**Here is where all starts according to error:**
https://github.com/yoannchb-pro/discord-phub/blob/main/discord-phub.js#L64

**Comment by Mlob666** [comment]
I copied all your code and the error is the "??" in the line Fixed with this: return this.typesByCategorie[category].includes(type) == false;

**Comment by yoannchb-pro** [comment]
Hi, thx for reporting this bug I'll check that this week ! During the wait you can come back to the previous version 
`npm i discord-phub@1.0.6`

**Comment by yoannchb-pro** [comment]
What is your node version ? The test are working well on my side. Mine is v14.17.5.

**Comment by Mlob666** [comment]
> What is your node version ? The test are working well on my side. Mine is v14.17.5.

12.22.10
